name = "lacurent"

main = "workers/save-house.js"

compatibility_date = "2026-05-19"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "lacurent-db"
database_id = "91b70c8a-3c11-4fe0-81ed-e3b64a075118"