-- Generated deterministically from commercial/data/energy_product_catalog_source_pack_v2.json
-- Staging smoke pack only; products with incomplete TEO evidence remain stored but receive no value metric.

INSERT OR REPLACE INTO energy_products (id,external_id,category_id,manufacturer,model,label,manufacturer_sku,gtin,intended_use,description,source_kind,source_url,evidence_status,catalog_version,observed_on,active,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160',NULL,'wall_insulation','Austrotherm','EPS A100 AF PLUS 160 mm','Austrotherm EPS A100 AF PLUS 160 mm','5945786200983',NULL,NULL,'','manufacturer_and_offer_sources','https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat','document_backed','energy-product-source-pack-v1','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_documents (document_id,product_id,document_type,title,issuer,declaration_number,standard_reference,revision,language,source_url,observed_on,sha256,parse_status,rights_note,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160:source:00','austrotherm-eps-a100-af-plus-160','manufacturer_product_page','manufacturer_product_page','Austrotherm',NULL,NULL,NULL,NULL,'https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat','2026-09-30',NULL,'partial','Link/reference only; source content is not redistributed.',CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160','thickness_mm','nominal',160,NULL,NULL,160,NULL,'austrotherm-eps-a100-af-plus-160:source:00','https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160','lambda_w_mk','nominal',0.03,NULL,NULL,0.03,NULL,'austrotherm-eps-a100-af-plus-160:source:00','https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160','package_area_m2','nominal',1.5,NULL,NULL,1.5,NULL,'austrotherm-eps-a100-af-plus-160:source:00','https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160','plate_area_m2','nominal',0.5,NULL,NULL,0.5,NULL,'austrotherm-eps-a100-af-plus-160:source:00','https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_offers (offer_id,product_id,supplier,supplier_sku,price_lei,price_basis,quantity,quantity_unit,vat_included,stock_status,source_url,observed_on,active,updated_at) VALUES ('austrotherm-eps-a100-af-plus-160:offer:00','austrotherm-eps-a100-af-plus-160','Filge',NULL,114.9,'lei_package',1.5,'m2',1,'unknown','https://filge.ro/produs/polistiren-grafitat-austrotherm-eps100-af-plus-16cm/','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_value_metrics (product_id,metric_key,comparison_scope,numerator_value,numerator_unit,denominator_price_lei,denominator_basis,metric_value,metric_unit,formula_version,source_signature,computed_at) VALUES ('austrotherm-eps-a100-af-plus-160','thermal_resistance_per_price','wall_insulation',5.333333333333334,'m2K/W',76.60000000000001,'lei_per_m2',0.06962576153176675,'R_added/(lei/m2)','energy-product-value-v1','https://www.austrotherm.ro/produse/austrotherm-eps/austrotherm-eps-a100-af-plus-grafitat|https://filge.ro/produs/polistiren-grafitat-austrotherm-eps100-af-plus-16cm/',CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO energy_products (id,external_id,category_id,manufacturer,model,label,manufacturer_sku,gtin,intended_use,description,source_kind,source_url,evidence_status,catalog_version,observed_on,active,updated_at) VALUES ('purmo-compact-c22-600x1000',NULL,'radiator','Purmo','Compact C22 600 x 1000','Purmo Compact C22 600 x 1000 mm',NULL,NULL,NULL,'','manufacturer_and_offer_sources','https://www.purmo.com/en/products/panels/compact.htm','document_backed','energy-product-source-pack-v1','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_documents (document_id,product_id,document_type,title,issuer,declaration_number,standard_reference,revision,language,source_url,observed_on,sha256,parse_status,rights_note,updated_at) VALUES ('purmo-compact-c22-600x1000:source:00','purmo-compact-c22-600x1000','manufacturer_product_page','manufacturer_product_page','Purmo',NULL,'EN 442',NULL,NULL,'https://www.purmo.com/en/products/panels/compact.htm','2026-09-30',NULL,'partial','Link/reference only; source content is not redistributed.',CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','height_mm','nominal',600,NULL,NULL,600,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','length_mm','nominal',1000,NULL,NULL,1000,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','heat_output_w_75_65_20','nominal',1709,NULL,NULL,1709,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','heat_output_w_70_55_20','nominal',1362,NULL,NULL,1362,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','radiator_exponent_n','nominal',1.3358,NULL,NULL,1.3358,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','working_pressure_bar','nominal',10,NULL,NULL,10,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('purmo-compact-c22-600x1000','max_temperature_c','nominal',110,NULL,NULL,110,NULL,'purmo-compact-c22-600x1000:source:00','https://www.purmo.com/en/products/panels/compact.htm','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_offers (offer_id,product_id,supplier,supplier_sku,price_lei,price_basis,quantity,quantity_unit,vat_included,stock_status,source_url,observed_on,active,updated_at) VALUES ('purmo-compact-c22-600x1000:offer:00','purmo-compact-c22-600x1000','Dedeman','2017064',509,'lei_unit',1,'unit',1,'unknown','https://www.dedeman.ro/ro/calorifer-otel-purmo-c22-600-x-1000-mm-accesorii-incluse/p/2017064','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_value_metrics (product_id,metric_key,comparison_scope,numerator_value,numerator_unit,denominator_price_lei,denominator_basis,metric_value,metric_unit,formula_version,source_signature,computed_at) VALUES ('purmo-compact-c22-600x1000','heat_output_per_price','radiator_dt50',1709,'W_dt50',509,'lei_unit',3.357563850687623,'W_dt50/lei','energy-product-value-v1','https://www.purmo.com/en/products/panels/compact.htm|https://www.dedeman.ro/ro/calorifer-otel-purmo-c22-600-x-1000-mm-accesorii-incluse/p/2017064',CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO energy_products (id,external_id,category_id,manufacturer,model,label,manufacturer_sku,gtin,intended_use,description,source_kind,source_url,evidence_status,catalog_version,observed_on,active,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640',NULL,'underfloor_pipe','Uponor','Comfort Pipe PLUS 16x2.0 640 m','Uponor Comfort Pipe PLUS 16x2.0 640 m','1062046',NULL,NULL,'','manufacturer_and_offer_sources','https://www.uponor.com/en-en/documents?country=RO&id=1062046','document_backed','energy-product-source-pack-v1','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_documents (document_id,product_id,document_type,title,issuer,declaration_number,standard_reference,revision,language,source_url,observed_on,sha256,parse_status,rights_note,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640:source:00','uponor-comfort-pipe-plus-16x2-640','manufacturer_product_page','manufacturer_product_page','Uponor',NULL,NULL,NULL,NULL,'https://www.uponor.com/en-en/documents?country=RO&id=1062046','2026-09-30',NULL,'partial','Link/reference only; source content is not redistributed.',CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640','package_length_m','nominal',640,NULL,NULL,640,NULL,'uponor-comfort-pipe-plus-16x2-640:source:00','https://www.uponor.com/en-en/documents?country=RO&id=1062046','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640','outer_diameter_mm','nominal',16,NULL,NULL,16,NULL,'uponor-comfort-pipe-plus-16x2-640:source:00','https://www.uponor.com/en-en/documents?country=RO&id=1062046','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640','wall_thickness_mm','nominal',2,NULL,NULL,2,NULL,'uponor-comfort-pipe-plus-16x2-640:source:00','https://www.uponor.com/en-en/documents?country=RO&id=1062046','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640','design_pressure_bar','nominal',6,NULL,NULL,6,NULL,'uponor-comfort-pipe-plus-16x2-640:source:00','https://www.uponor.com/en-en/documents?country=RO&id=1062046','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640','design_temperature_c','nominal',70,NULL,NULL,70,NULL,'uponor-comfort-pipe-plus-16x2-640:source:00','https://www.uponor.com/en-en/documents?country=RO&id=1062046','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_offers (offer_id,product_id,supplier,supplier_sku,price_lei,price_basis,quantity,quantity_unit,vat_included,stock_status,source_url,observed_on,active,updated_at) VALUES ('uponor-comfort-pipe-plus-16x2-640:offer:00','uponor-comfort-pipe-plus-16x2-640','Shop-Einstal',NULL,5,'lei_per_m',1,'m',1,'unknown','https://www.shop-einstal.ro/tevi-si-fitinguri/teava-pex-fitinguri/teava-pe-xa-uponor-comfort-pipe-plus-16x2-41689301841.html','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_value_metrics (product_id,metric_key,comparison_scope,numerator_value,numerator_unit,denominator_price_lei,denominator_basis,metric_value,metric_unit,formula_version,source_signature,computed_at) VALUES ('uponor-comfort-pipe-plus-16x2-640','length_per_price','underfloor_pipe',640,'m',3200,'lei_package',0.2,'m/lei','energy-product-value-v1','https://www.uponor.com/en-en/documents?country=RO&id=1062046|https://www.shop-einstal.ro/tevi-si-fitinguri/teava-pex-fitinguri/teava-pe-xa-uponor-comfort-pipe-plus-16x2-41689301841.html',CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO energy_products (id,external_id,category_id,manufacturer,model,label,manufacturer_sku,gtin,intended_use,description,source_kind,source_url,evidence_status,catalog_version,observed_on,active,updated_at) VALUES ('zehnder-comfoair-q350-hrv',NULL,'hrv_unit','Zehnder','ComfoAir Q350 HRV','Zehnder ComfoAir Q350 HRV',NULL,NULL,NULL,'','manufacturer_and_offer_sources','https://www.international.zehnder-systems.com/en/comfortable-indoor-ventilation/products/units/ventilation-units-up-to-600-m3/h/zehnder-comfoair-q350-tr','source_backed','energy-product-source-pack-v1','2026-09-30',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_documents (document_id,product_id,document_type,title,issuer,declaration_number,standard_reference,revision,language,source_url,observed_on,sha256,parse_status,rights_note,updated_at) VALUES ('zehnder-comfoair-q350-hrv:source:00','zehnder-comfoair-q350-hrv','manufacturer_product_page','manufacturer_product_page','Zehnder',NULL,NULL,NULL,NULL,'https://www.international.zehnder-systems.com/en/comfortable-indoor-ventilation/products/units/ventilation-units-up-to-600-m3/h/zehnder-comfoair-q350-tr','2026-09-30',NULL,'partial','Link/reference only; source content is not redistributed.',CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('zehnder-comfoair-q350-hrv','max_airflow_m3h_at_200_pa','nominal',350,NULL,NULL,350,NULL,'zehnder-comfoair-q350-hrv:source:00','https://www.international.zehnder-systems.com/en/comfortable-indoor-ventilation/products/units/ventilation-units-up-to-600-m3/h/zehnder-comfoair-q350-tr','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_documents (document_id,product_id,document_type,title,issuer,declaration_number,standard_reference,revision,language,source_url,observed_on,sha256,parse_status,rights_note,updated_at) VALUES ('zehnder-comfoair-q350-hrv:source:01','zehnder-comfoair-q350-hrv','manufacturer_technical_catalog','manufacturer_technical_catalog','Zehnder',NULL,NULL,NULL,NULL,'https://newsletter.zehnder-systems.com/upload/prj/datasheet/ZehnderComfosystems_Technik-Katalog04-2022-it_lores.pdf','2026-09-30',NULL,'partial','Link/reference only; source content is not redistributed.',CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('zehnder-comfoair-q350-hrv','sfp_wh_m3_at_350_m3h_100pa','nominal',0.3,NULL,NULL,0.3,NULL,'zehnder-comfoair-q350-hrv:source:01','https://newsletter.zehnder-systems.com/upload/prj/datasheet/ZehnderComfosystems_Technik-Katalog04-2022-it_lores.pdf','source_backed',1,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_properties (product_id,property_key,context_key,numeric_value,text_value,unit,normalized_numeric_value,normalized_unit,source_document_id,source_locator,confidence,is_teo_input,updated_at) VALUES ('zehnder-comfoair-q350-hrv','electrical_power_w_at_350_m3h_100pa','nominal',106,NULL,NULL,106,NULL,'zehnder-comfoair-q350-hrv:source:01','https://newsletter.zehnder-systems.com/upload/prj/datasheet/ZehnderComfosystems_Technik-Katalog04-2022-it_lores.pdf','source_backed',0,CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO energy_product_offers (offer_id,product_id,supplier,supplier_sku,price_lei,price_basis,quantity,quantity_unit,vat_included,stock_status,source_url,observed_on,active,updated_at) VALUES ('zehnder-comfoair-q350-hrv:offer:00','zehnder-comfoair-q350-hrv','ventilatiecurecuperarecaldura.ro',NULL,21713,'lei_unit',1,'unit',1,'unknown','https://ventilatiecurecuperarecaldura.ro/product-category/sisteme-centralizate-cu-recuperator-de-caldura/zehnder-comfoair/','2026-09-30',1,CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO energy_product_import_batches (batch_id,source_name,source_url,category_id,imported_at,product_count,document_count,property_count,image_count,offer_count,status,note) VALUES ('energy-product-source-pack-v1:2026-09-30:smoke','repo_source_pack',NULL,NULL,CURRENT_TIMESTAMP,4,5,19,0,4,'imported','Initial cross-category staging smoke pack; 3 product(s) have complete category-local value metrics.');

