name = "lacurent-teo-router"
main = "worker.mjs"
compatibility_date = "2026-09-28"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "lacurent-db"
database_id = "91b70c8a-3c11-4fe0-81ed-e3b64a075118"

[[services]]
binding = "TEO_A"
service = "lacurent-teo-shard-a"
remote = true

[[services]]
binding = "TEO_B"
service = "lacurent-teo-shard-b"
remote = true

[[services]]
binding = "TEO_C"
service = "lacurent-teo-shard-c"
remote = true

[[services]]
binding = "TEO_D"
service = "lacurent-teo-shard-d"
remote = true

[[routes]]
pattern = "lacurent.com/api/optimization/home-lab/v3/*"
zone_name = "lacurent.com"

[[routes]]
pattern = "lacurent.com/api/optimization/home-lab/v4/*"
zone_name = "lacurent.com"
