name = "lacurent-commercial-v2"
main = "src/worker.py"
compatibility_date = "2026-08-29"
compatibility_flags = ["python_workers"]
workers_dev = true

[[routes]]
pattern = "lacurent.com"
custom_domain = true

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json", "**/*.geojson"]
fallthrough = true
